# Generated by Django 5.2.1 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nation_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Operation_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.DateTimeField()),
                ('search_id', models.CharField(max_length=100)),
                ('record_info', models.CharField(max_length=100)),
                ('open_state', models.BooleanField(default=False)),
                ('operation_for', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pay_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay_time', models.DateTimeField()),
                ('pay_bank_name', models.CharField(max_length=50)),
                ('pay_bank_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='position_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verify_state', models.BooleanField(default=False)),
                ('email_verify_time', models.DateTimeField(default=None)),
                ('person_verify_state', models.SmallIntegerField(default=0)),
                ('person_verify_time', models.CharField(default=None, max_length=200)),
                ('person_verify_id', models.CharField(default=None, max_length=100)),
                ('active_state', models.SmallIntegerField(default=0)),
                ('active_time', models.DateTimeField()),
                ('active_duration', models.CharField(default=None, max_length=100)),
                ('logout_state', models.SmallIntegerField(default=0)),
                ('logout_time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='university_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('university_web', models.CharField(max_length=200)),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.nation_tab')),
            ],
        ),
        migrations.CreateModel(
            name='user_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.SmallIntegerField()),
                ('pay_state', models.SmallIntegerField()),
                ('state_change_time', models.DateTimeField()),
                ('validity_period', models.DateTimeField()),
                ('is_validity', models.BooleanField(default=0)),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.pay_tab')),
            ],
        ),
        migrations.CreateModel(
            name='users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.IntegerField(default=3)),
                ('birth_date', models.DateTimeField()),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.position_tab')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.university_tab')),
            ],
        ),
        migrations.CreateModel(
            name='login_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userPass', models.CharField(max_length=30)),
                ('userEmail', models.CharField(max_length=50)),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.operation_record')),
                ('ulevel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.user_level')),
                ('ustatus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.user_status')),
                ('userinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersInfo.users_info')),
            ],
        ),
    ]
